LaundryERP/LaundryERP/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),
    path('ordenes/', include(('ordenes.urls', 'ordenes'), namespace='ordenes')),
    path('ventas/', include(('ventas.urls', 'ventas'), namespace='ventas')),
    path('reportes/', include(('reportes.urls', 'reportes'), namespace='reportes')),
]

LaundryERP/ordenes/urls.py
from django.urls import path
from . import views

app_name='ordenes'

urlpatterns = [
    path('', views.lista_ordenes, name='lista_ordenes'),
    path('detalle/<int:id>', views.detalle_orden, name='detalle_orden'),
    path('crear/', views.crear_orden, name='crear_orden'),
    path('eliminar/<int:id>', views.eliminar_orden, name='eliminar_orden'),
    path('actualizar_estado/<int:id>', views.actualizar_estado, name='actualizar_estado'),   
]

LaundryERP/ventas/urls.py
from django.urls import path
from . import views

app_name='ventas'

urlpatterns = [
    path('', views.lista_venta, name='lista_ventas'),
    path('detalle/<int:id>', views.detalle_venta, name='detalle_venta'),
    path('crear/', views.crear_venta, name='crear_venta'),
    path('eliminar/<int:id>', views.eliminar_venta, name='eliminar_venta'),
    path('actualizar_venta/<int:id>', views.actualizar_venta, name='actualizar_venta'),
]

LaundryERP/ordenes/models.py
from django.db import models
from usuarios.models import Usuario

# Create your models here.
class Prenda(models.Model):
    TIPO_PRENDA_CHOICES =  [
        ('pantalon', 'Pantalón'),
        ('camisa', 'Camisa'),
        ('saco', 'Saco'),
        ('calcetines', 'Calcetines'),
        ('zapatos', 'Zapatos'),
        ('medias', 'Medias'),
        ('blusa', 'Blusa'),
        ('chaleco', 'Chaleco'),
        ('traje', 'Traje'),
        ('pantalones_jeans', 'Pantalones Jeans'),
        ('chaquetas', 'Chaquetas'),
        ('jeans', 'Jeans'),
        ('jersey', 'Jersey'),
        ('sweater', 'Sweater'),
        ('t-shirt', 'T-Shirt'),
        ('buzo', 'Buzo'),
        ('sudadera', 'Sudadera'),
        ('pantalones_shorts', 'Pantalones Shorts'),
    ]
    tipo_prenda=models.CharField(max_length=50, choices=TIPO_PRENDA_CHOICES), 
    precio=models.DecimalField(max_digits=10, decimal_places=2)
    descripcion=models.TextField()

    def __str__(self):
        return f'{self.tipo_prenda} - {self.precio}'
# crear el modelo cliente 
class Cliente(models.Model):
    nombre=models.CharField(max_length=100)
    telefono=models.CharField(max_length=15)
    correo=models.EmailField(unique=True) #con unique=true se establece para que los correos sean unicos
    direccion=models.TextField()
    
    def __str__(self):
        return self.nombre

     
#Creacion de modelo de Orden de servicio 
class OrdenDeServicio(models.Model):
    ESTADOS=[
        ('pendiente', 'Pendiente'),
        ('proceso', 'En Proceso'),
        ('completada', 'Completada')
    ]

    cliente=models.ForeignKey(Cliente, on_delete=models.CASCADE)
    empleado=models.ForeignKey(Usuario, on_delete=models.SET_NULL,null=True)
    prendas=models.ManyToManyField(Prenda, related_name='ordenes'), #Se asocia mas de una prenda a la orden y la misma prenda puede estar en varias ordenes
    fecha_creacion=models.DateTimeField(auto_now_add=True) # no se requiere agregar mas parametros 
    estado=models.CharField(max_length=20 , choices=ESTADOS, default='pendiente') #'pendiente', va el valor no la etiqueta
    total=models.DecimalField(max_digits=10, decimal_places=2, default=0)
    pago_realizado=models.BooleanField(default=False)

    #Calculo del total de la orden sumando los precios de las prendas asociadas
    def calculo_total(self):
        self.total=sum(prenda.precio for prenda in self.prendas.all())
        self.save()
        return self.total


    def __str__(self):   # devielve cadena de caracteres 
        return f"Orden #{self.id} - {self.cliente.nombre} - {self.estado} - {self.total}"

LaundryERP/ordenes/forms.py
from django import forms
from .models import OrdenDeServicio, Prenda, Cliente 
from usuarios.models import Usuario  
from django.contrib.auth.forms import AuthenticationForm


class OrdenDeServicioForm(forms.ModelForm):
    class Meta:  
        model = OrdenDeServicio
        fields = ['cliente', 'empleado', 'prendas', 'estado']
        
    cliente = forms.ModelChoiceField(queryset=Cliente.objects.all(), empty_label='Seleccione un Cliente', widget=forms.Select(attrs={'class': 'form-control'}))
    empleado = forms.ModelChoiceField(queryset=Usuario.objects.filter(rol='empleado'), empty_label='Seleccione un Empleado', widget=forms.Select(attrs={'class': 'form-control'}))
    estado = forms.ChoiceField(choices=OrdenDeServicio.ESTADOS, initial='pendiente', widget=forms.Select(attrs={'class': 'form-control'}))
    prendas = forms.ModelMultipleChoiceField(queryset=Prenda.objects.all(), widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-control'}))
    def __init__(self, *args, **kwargs):
        super(OrdenDeServicioForm,self).__init__(*args, **kwargs)
        self.fields['estado'].widget.attrs.update({'class': 'form-control'})
        self.fields['cliente'].widget.attrs.update({'class': 'form-control'})
        self.fields['empleado'].widget.attrs.update({'class': 'form-control'})
        self.fields['prendas'].widget.attrs.update({'class': 'form-control'})
        
       

        

LaundryERP/ordenes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import OrdenDeServicio 
from .forms import OrdenDeServicioForm
from django.contrib import messages

# Create your views here.

def lista_ordenes(request):
    ordenes = OrdenDeServicio.objects.all()
    return render(request,'ordenes/lista_ordenes.html',{'ordenes':ordenes})

def detalle_orden(request, id):
    orden = get_object_or_404(OrdenDeServicio, id=id)
    return render(request,'ordenes/detalle_orden.html',{'orden':orden})

def crear_orden(request):
    if request.method == 'POST':
        form = OrdenDeServicioForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'La Orden ha sido creada con éxito!')
            return redirect('ordenes:lista_ordenes')
    else:
        form = OrdenDeServicioForm()      
    return render(request,'ordenes/crear_orden.html', {'form':form})
 
def actualizar_estado(request, id):
    orden = get_object_or_404(OrdenDeServicio, id=id)
    if request.method == 'POST':
        estado = request.post.get('estado')
        orden.estado = estado
        orden.save()
        messages.success(request, f'La Orden {orden.id}  ha sido actualizado a {estado}')
        return redirect('ordenes:detalle_orden.html', id=orden.id)
        
    return render(request, 'ordenes/actualizar_estado.html', {'orden': orden})

def eliminar_orden(request, id):
    orden = get_object_or_404(OrdenDeServicio, id=id)
    if request.method == 'POST':
        orden.delete()
        messages.success(request, f'La Orden {orden.id} ha sido eliminada')
        return redirect('ordenes:lista_ordenes')
    return render(request, 'ordenes/eliminar_orden.html', {'orden': orden})

LaundryERP/ordenes/templates/ordenes/actualizar_estado.html
{% extends 'base.html' %}
{% block title %}Actualizar Orden{% endblock %}
{%block content%}
<h1>Actualizar el Estado de la Orden</h1>

<p><strong>Cliente:</strong> {{ orden.cliente.nombre }}</p>

<p><strong>Empleado:</strong> {{ orden.Empleado.username }}</p>

<p><strong>Estado:</strong> {{ orden.estado }}</p>

<p><strong>Fecha de creación:</strong>{{ orden.fecha_creacion }}</p>

<p><strong>Total:</strong> ${{ orden.total }}</p>

<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="estado">Actualizar Estado:</label>
        <select class="form-control" id="estado" name="estado">
            <option value="pendiente" {% if orden.estado =='pendiente' %} selected  {% endif %}>Pendiente</option>
            <option value="proceso" {% if orden.estado =='proceso' %} selected  {% endif %}>En Proceso</option>
            <option value="finalizado" {% if orden.estado =='conpletada' %} selected  {% endif %}>Completada</option>  
        </select>


    </div>
    <button type="submit" class="btn btn-primary">Actualizar</button>
</form>

{% endblock %}

LaundryERP/ordenes/templates/ordenes/crear_orden.html
{% extends 'base.html' %}
{% block title %}Crear Orden{% endblock %}
{%block content%}
<h1>Crear Nueva Orden</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear Orden</button>
</form>
{% endblock %}

LaundryERP/ordenes/templates/ordenes/detalle_orden.html
{% extends 'base.html' %}
{% block title %}Detalle de la Orden{% endblock %}
{%block content%}
<h1>Detalle de la Orden {{orden.id}}</h1>

<p><strong>Pedido realizado por:</strong> {{ orden.cliente.nombre }}</p>

<p><strong>Pedido tramitado por:</strong> {{ orden.Empleado.username }}</p>

<p><strong>Estado:</strong> {{ orden.estado }}</p>

<p><strong>Fecha de creación:</strong>{{ orden.fecha_creacion }}</p>

<p><strong>Total:</strong> ${{ orden.total }}</p>

<a href="{% url 'ordenes:actualizar_estado' orden.id %}" class="btn btn-warning">Actualizar Estado</a> 

<a href="{% url 'ordenes:eliminar_orden' orden.id %}" class="btn btn-danger" onclick="return confirm('¿Esta seguro que desea Eliminar esta orden?')">Eliminar Orden</a> 

{% endblock %}

LaundryERP/ordenes/templates/ordenes/eliminar_orden.html
{% extends 'base.html' %}
{% block title %}Eliminar Orden{% endblock %}
{%block content%}
<h1>Confirmar Eliminacion de orden</h1>

<p>¿Estas seguro de eliminar la orden con el numero {{ order.id }}?</p>

<form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirmar Eliminacion</button>
    <a href="{% url 'ordenes:lista_ordenes'%}" class="btn btn-secondary">Cancelar</a>
</form>

{% endblock %}

LaundryERP/ordenes/templates/ordenes/lista_ordenes.html
{% extends 'base.html' %}
{% block title %} Listado de Ordenes {% endblock %}
{%block content%}
<div class="container mt-4"> 

    <h2>Lista de Ordenes</h2>
    <a href="{% ordenes:crear_orden %}" class="btn btn-primary">Crear Nueva Orden</a>
    <table class="table mt-4">
        <thead>
            <tr>
                <th>ID</th>
                <th>Cliente</th>
                <th>Empleado</th>
                <th>Estado</th>
                <th>Fecha de Creacion</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for orden in ordenes %}
            <tr>
                <td>{{ orden.id }}</td>
                <td>{{ orden.cliente.nombre }}</td>
                <td>{{ orden.empleado.username }}</td>
                <td>{{ orden.estado }}</td>
                <td>{{ orden.fecha_creacion }}</td>
                <td>
                    <a href="{% url 'ordenes:detalle_orden' orden.id %}" class="btn btn-info">Detalles</a>
                    <a href="{% url 'ordenes:actualizar_orden' orden.id %}" class="btn btn-warning">Editar</a>
                    <a href="{% url 'ordenes:eliminar_orden' orden.id %}" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
            {% endfor %}


        </tbody>

    </table>
</div>
{% endblock %}